require('dotenv').config()
const { message } = require('telegraf/filters')
const { BOT } = require('./config/bot.config')
const { startCommand } = require('./commands/start.command')
const { helpCommand } = require('./commands/help.command')
const { settingsCommand } = require('./commands/settings.command')
const { textMessageHandler } = require('./handler/text.handler')
const { newChatTitle } = require('./handler/newChatTitle.handler')
const { registerSettingsActions } = require('./actions/settings.actions')
const { registerInsults } = require('./config/insults.config')
const { registerChats } = require('./config/chats.config')
const { launchBot } = require('./config/launch.config')

BOT.start(startCommand)
BOT.help(helpCommand)
BOT.settings(settingsCommand)

BOT.on(message('text'), textMessageHandler)
BOT.on('new_chat_title', newChatTitle)

registerSettingsActions()
registerInsults()
registerChats()
launchBot()
